// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'customer_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Customer _$CustomerFromJson(Map<String, dynamic> json) => Customer(
      id: json['id'] as String,
      code: json['code'] as String,
      accountGroup: json['account_group'] as String,
      customerType: json['customer_type'] as String?,
      branch: json['branch'] as String?,
      customerGroup: json['customer_group'] as String?,
      customerClass: json['customer_class'] as String?,
      name: json['name'] as String,
      companyCode: json['company_code'] as String?,
      sectorCode: json['sector_code'] as String?,
      phone: json['phone'] as String?,
      mobile: json['mobile'] as String?,
      fax: json['fax'] as String?,
      email: json['email'] as String?,
      website: json['website'] as String?,
      whatsapp: json['whatsapp'] as String?,
      address: json['address'] as String?,
      neighborhood: json['neighborhood'] as String?,
      street: json['street'] as String?,
      avenue: json['avenue'] as String?,
      openAddress: json['open_address'] as String?,
      city: json['city'] as String?,
      district: json['district'] as String?,
      postalCode: json['postal_code'] as String?,
      country: json['country'] as String?,
      latitude: json['latitude'] as String?,
      longitude: json['longitude'] as String?,
      locationName: json['location_name'] as String?,
      taxOfficeCode: json['tax_office_code'] as String?,
      taxOfficeName: json['tax_office_name'] as String?,
      taxNumber: json['tax_number'] as String?,
      taxCategory: json['tax_category'] as String?,
      taxLiabilityType: json['tax_liability_type'] as String?,
      vatWithholdingRate: json['vat_withholding_rate'] as String?,
      incomeTaxWithholding: json['income_tax_withholding'] as String?,
      corporateTaxWithholding: json['corporate_tax_withholding'] as String?,
      stampTax: json['stamp_tax'] as String?,
      taxExempt: json['tax_exempt'] as String?,
      eInvoiceActive: json['e_invoice_active'] as String?,
      eArchiveActive: json['e_archive_active'] as String?,
      eArchiveScenario: json['e_archive_scenario'] as String?,
      eLedgerActive: json['e_ledger_active'] as String?,
      paymentTerms: json['payment_terms'] as String?,
      paymentMethod: json['payment_method'] as String?,
      currency: json['currency'] as String? ?? 'TRY',
      creditLimit: (json['credit_limit'] as num?)?.toDouble(),
      riskCategory: json['risk_category'] as String?,
      salesOrg: json['sales_org'] as String?,
      distributionChannel: json['distribution_channel'] as String?,
      division: json['division'] as String?,
      priceList: json['price_list'] as String?,
      incoterms: json['incoterms'] as String?,
      shippingCondition: json['shipping_condition'] as String?,
      iban: json['iban'] as String?,
      status: json['status'] as String? ?? 'Aktif',
      createdAt: json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
      updatedAt: json['updated_at'] == null
          ? null
          : DateTime.parse(json['updated_at'] as String),
      needsSync: json['needs_sync'] as bool? ?? false,
    );

Map<String, dynamic> _$CustomerToJson(Customer instance) => <String, dynamic>{
      'id': instance.id,
      'code': instance.code,
      'account_group': instance.accountGroup,
      'customer_type': instance.customerType,
      'branch': instance.branch,
      'customer_group': instance.customerGroup,
      'customer_class': instance.customerClass,
      'name': instance.name,
      'company_code': instance.companyCode,
      'sector_code': instance.sectorCode,
      'phone': instance.phone,
      'mobile': instance.mobile,
      'fax': instance.fax,
      'email': instance.email,
      'website': instance.website,
      'whatsapp': instance.whatsapp,
      'address': instance.address,
      'neighborhood': instance.neighborhood,
      'street': instance.street,
      'avenue': instance.avenue,
      'open_address': instance.openAddress,
      'city': instance.city,
      'district': instance.district,
      'postal_code': instance.postalCode,
      'country': instance.country,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'location_name': instance.locationName,
      'tax_office_code': instance.taxOfficeCode,
      'tax_office_name': instance.taxOfficeName,
      'tax_number': instance.taxNumber,
      'tax_category': instance.taxCategory,
      'tax_liability_type': instance.taxLiabilityType,
      'vat_withholding_rate': instance.vatWithholdingRate,
      'income_tax_withholding': instance.incomeTaxWithholding,
      'corporate_tax_withholding': instance.corporateTaxWithholding,
      'stamp_tax': instance.stampTax,
      'tax_exempt': instance.taxExempt,
      'e_invoice_active': instance.eInvoiceActive,
      'e_archive_active': instance.eArchiveActive,
      'e_archive_scenario': instance.eArchiveScenario,
      'e_ledger_active': instance.eLedgerActive,
      'payment_terms': instance.paymentTerms,
      'payment_method': instance.paymentMethod,
      'currency': instance.currency,
      'credit_limit': instance.creditLimit,
      'risk_category': instance.riskCategory,
      'sales_org': instance.salesOrg,
      'distribution_channel': instance.distributionChannel,
      'division': instance.division,
      'price_list': instance.priceList,
      'incoterms': instance.incoterms,
      'shipping_condition': instance.shippingCondition,
      'iban': instance.iban,
      'status': instance.status,
      'created_at': instance.createdAt?.toIso8601String(),
      'updated_at': instance.updatedAt?.toIso8601String(),
      'needs_sync': instance.needsSync,
    };
